### ISSUE TITLE
ERROR Error: Uncaught (in promise): RangeError: Wrong length! RangeError: Wrong length!     at validateArrayBufferArguments

### ISSUE THREAD

**Issue by Neetesh1** [andreyvit/json-diff#90]
json-diff was working perfectly fine with my angular 11 but when i migrated to 12. it started giving errors for assert. So I installed it ( npm i assert) after doing this now when i run ng serve  it is givng an error in browser console. 

```
core.js:6498 ERROR Error: Uncaught (in promise): RangeError: Wrong length!
RangeError: Wrong length!
    at validateArrayBufferArguments (core.js:5566:40)
    at new ArrayBuffer (core.js:5656:30)
    at 88048 (types.js:206:1)
    at __webpack_require__ (bootstrap:19:1)
    at 94655 (util.js:467:1)
    at __webpack_require__ (bootstrap:19:1)
    at 15025 (assertion_error.js:35:16)
    at __webpack_require__ (bootstrap:19:1)
    at 25652 (assert.js:36:22)
    at __webpack_require__ (bootstrap:19:1)
    at resolvePromise (zone.js:1211:1)
    at resolvePromise (zone.js:1165:1)
    at zone.js:1278:1
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.js:28679:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:585:1)
```

Please check if your version if this is not echma script.
